### ISSUE TITLE
influenza_na.dat - duplicate f:genbank and f:genbank_id

### ISSUE THREAD

**Issue by j23414** [flu-crew/octofludb#2]
Is there a reason for having both `f:genbank` and `f:genbank_id`?

For example:

fid:mg12345 f:genbank "MG12345"
fid:mg12345 f:genbank_id "MG12345"

They return the same thing...

**Comment by arendsee** [comment]
This is now fixed. GenBank IDs are only referred to now as `f:genbank_id`.
